name: Hello World Deployment Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Read permission for the repository content
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Hello World script
        run: python hello.py  # Runs the hello.py script

  staging:
    runs-on: ubuntu-latest
    needs: testing  # Ensure staging runs after testing
    permissions:
      contents: write  # Write permission for staging
    environment: staging  # Use the staging environment with manual approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Hello World script
        run: python hello.py  # Runs the hello.py script

  production:
    runs-on: ubuntu-latest
    needs: staging  # Ensure production runs after staging
    permissions:
      contents: write  # Write permission for production
    environment: production  # Use the production environment with manual approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Hello World script
        run: python hello.py  # Runs the hello.py script
