name: SonarQube Scan

on:
  push:
    branches:
      - main  # Trigger SonarQube scan on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger SonarQube scan on PRs targeting the main branch

jobs:
  sonarcloud:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'         # Specify Java version
          distribution: 'adoptopenjdk'  # Specify the distribution of Java

      - name: Install SonarScanner
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
      
      - name: SonarQube Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.host.url=http://65.2.146.57:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
